### DISCUSSION TITLE
Why does emotion have to repeat all css properties for every little change?

### DISCUSSION THREAD

**Discussion by faradaytrs** [emotion-js/emotion#2746] [General]
For example, we have two blocks:
````jsx
const divCss = css`
    background-color: red;
    padding: 10px;
    border: 1px solid blue;
`;

<div css={divCss}></div>
<div css={divCss}></div>
````
This will result in two divs having the same classname, which is expected.
But if we add one dynamic variable:
````jsx
const divCss = css`
    background-color: red;
    padding: 10px;
    border: 1px solid blue;
`;

<div css={[divCss, {color: "yellow"}]}></div>
<div css={[divCss, {color: "white"}]}></div>
````
It will result in them having completely different classnames, and although most of css properties they use are the same and obviously static, it will copy paste them many times under different classname.

If we have many versions of the same element on the page with a lot of static css and just one line difference it will result in large build size.

Why can't emotion detect static part of the css and detect separate classname for static and dynamic styles?

It would be awesome if it generates:
````css
.classname1 {
    background-color: red;
    padding: 10px;
    border: 1px solid blue;
}
.classname2 {
    color: yellow;
}
.classname3 {
    color: white;
}

And then just combines them accordingly:
````html
<div classname="classname1 classname2"></div>
<div classname="classname1 classname2"></div>
````

I can kinda manually achieve such result by using className property in combination with cx. But it will generate styles in runtime instead. Only css property is handled by compiler.
