### ISSUE TITLE
<style> tags grow infinitely large in development when css is reused/toggled

### ISSUE THREAD

**Issue by jaredLunde** [emotion-js/emotion#1296]
- `emotion` version: `@emotion/core@10.0.10`
- `react` version: `16.8.5`

**Relevant code:**

```javascript
const on = css`background: pink;`
const off = css`background: blue;`
const Toggle = props => {
   const [value, toggle] = useToggle(true, false)
   return <button css={value === true ? on : off} onClick={toggle}>Toggle</button>
}
```

**What you did:**
I toggled between css values using a setup with @emotion/babel-preset-css-prop and @emotion/core.  The options for @emotion/babel-preset-css-prop are `{"sourceMap": true, "useBuiltIns": true, "autoLabel": true}`

**What happened:**
When toggling between CSS defs in `development`, styles get appended infinitely until eventually the browser buckles to the load and crashes. So far as I can tell this does not happen in `production`.

Toggle 1
```css
/* this also creates a new <style> tag in the <head> */
<style data-emotion="css">
.css-7pibqx-on{background:pink;}
</style>
``` 
Toggle 2
```css
/* this also creates a new <style> tag in the <head> */
<style data-emotion="css">
.css-pBwe1d-on{background:pink;background:pink;}
</style>
``` 
Toggle 3
```css
/* this also creates a new <style> tag in the <head> */
<style data-emotion="css">
.css-zGebql-on{background:pink;background:pink;background:pink;}
</style>
``` 

You get the picture. As I said, this behavior continues until the browser window crashes. Unfortunately this is impossible to reproduce in code sandbox because one can't use @emotion/babel-preset-css-prop. 

Here is an example of what I see in the document `<head>`
https://www.dropbox.com/s/jgy27wj8pa56d9b/Screenshot%202019-03-29%2009.48.53.png?dl=0

It just keeps growing and growing like that despite receiving the exact same values in the `css` prop.

**Reproduction:**
See above. It doesn't happen in [this CodeSandbox](https://codesandbox.io/s/k556r7wom7) I'm assuming because it's not using the babel preset.
