### ISSUE TITLE
Invalid CSS generated in styles containing background-image: url() with parentheses, nested in media queries

### ISSUE THREAD

**Issue by KaeruCT** [emotion-js/emotion#1313]
- `emotion` version: 10.10.9
- `react` version: 16.8.3

**Relevant code:**

```javascript
const imgUrl = 'image_(1).jpg'; // filename with PARENTHESES

{
  "@media only screen and (max-width: 320px)": {
    backgroundImage: `url("${imgUrl}")`,
    border: "red 4px solid"
  },
  "@media only screen and (min-width: 321px)": {
    backgroundImage: `url("${imgUrl}")`,
    border: "blue 4px solid"
  }
}

```

**What you did:**
Used the object above as a style for my component. I expected it to generate the media query CSS correctly.

**What happened:**

It fails to close the media queries, generating invalid css:
```css
@media only screen and (max-width:320px){
    .css-1tdq7c8{
        background-image:url("https://cdn.hellofresh.com/au/cms/landing_pages/main_header_(1).jpg");
        border:red 4px solid;
    }
    @media only screen and (min-width:321px){
        .css-1tdq7c8{
            background-image:url("https://cdn.hellofresh.com/au/cms/landing_pages/main_header_(1).jpg");
            border:blue 4px solid;
        }
    }
}
```

I think the result should be this instead:
```css
@media only screen and (max-width:320px){
    .css-1tdq7c8{
        background-image:url("https://cdn.hellofresh.com/au/cms/landing_pages/main_header_(1).jpg");
        border:red 4px solid;
    }
}
@media only screen and (min-width:321px){
    .css-1tdq7c8{
        background-image:url("https://cdn.hellofresh.com/au/cms/landing_pages/main_header_(1).jpg");
        border:blue 4px solid;
    }
}
```

**Reproduction:**

https://codesandbox.io/s/jprj8oqp2y

**Problem description:**

The generated CSS is missing a `}` to close the first media query.

**Suggested solution:**

None so far as I'm not familiar with the emotion codebase, but I'm willing to create a fix with some guidance.
