### ISSUE TITLE
Implement LESS/SCSS support

### ISSUE THREAD

**Issue by aej11a** [emotion-js/emotion#1416]
**The problem**

It would be much easier to write inline styles if LESS/SCSS were supported

**Proposed solution**

Implement LESS or SCSS as alternatives to the `css` inline modifier imported from emotion/core

**Comment by Andarist** [comment]
That would increase complexity and bundlesize dramatically. With emotion you already have full-blown language (javascript) at your disposal to create your styles and there is no much need to introduce any other special syntax (even if it's as familiar to people as less/scss)

**Comment by kimbaudi** [comment]
Here is an example of how I converted SCSS to emotion in a React application:

**scss**

```scss
.nav {
  background: lightgreen;

  ul {
    display: inline-flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: flex-start;
    margin: 0;
    padding: 0;
    list-style-type: none;

    li {
      padding: 0.25rem 0.5rem;
      background: mintcream;

      &:not(:last-child) {
        margin-right: 1rem;
      }
    }
  }
}
```

**react**

```jsx
import React from 'react'
import { Link } from 'gatsby'
import styled from '@emotion/styled'

const Nav = styled.nav({
  backgroundColor: 'lightgreen',
})

const Ul = styled.ul({
  display: 'inline-flex' /* flex | inline-flex */,
  flexDirection: 'row' /* ? | ? */,
  flexWrap: 'wrap' /* ? | ? */,
  justifyContent: 'flex-start',
  margin: 0,
  padding: 0,
  listStyleType: 'none' /* ? | ? */,
})

const Li = styled.li({
  padding: '0.25rem 0.5rem',
  backgroundColor: 'mintcream',
  '&:not(:last-child)': {
    marginRight: '1rem',
    backgroundColor: 'red',
  },
})

const Navigation = () => (
  <Nav>
    <Ul>
      <Li>
        <Link to={'/'}>Home</Link>
      </Li>
      <Li>
        <Link to={'/about'}>About</Link>
      </Li>
    </Ul>
  </Nav>
)
export default Navigation
```
