### ISSUE TITLE
Media query in a base component not properly overridden

### ISSUE THREAD

**Issue by slopes321** [emotion-js/emotion#1460]
**Current behavior:**

Take this `BaseBox` definition that provides yellow background for mobile (width below 768px) and red background for desktop (width of 768px and above):
```
const BaseBox = styled('div')`
  ${({ theme }) => `
    background-color: yellow;
    @media screen and (min-width: 768px) {
      background-color: red;
    }
  `}
`;
```

Then define `BlueBox` with the following `background-color` override, which should apply to all viewport widths:
```
const BlueBox = styled(BaseBox)`
  background-color: blue;
`;
```

We'd expect `BlueBox` to always have a blue background regardless of viewport width, and never yellow or red. However, we get a blue background for mobile (expected) and red background for desktop (not expected).

**To reproduce:**

See https://codesandbox.io/s/emotion-issue-template-91sn9

Try adjusting the viewport width below 768px and above 768px.

**Expected behavior:**

Component background is blue for all viewport widths.

**Actual behavior:**

Component background is blue below 768px viewport width; red otherwise.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.14

**Comment by Andarist** [comment]
That is very much expected by using this composition mechanism (`styled(BaseBox)`) you tell emotion to take **everything** defined in `BaseBox` and add some styles which you put into tagged template call. You can't wipeout what has been already defined in BaseBox, unless you override it - but you have to do it for the same "position". Like in your example you have successfully overridden background-color for a default output class, but you left media rule untouched, so it still applies for the new component.

**Comment by bukowskiadam** [comment]
👋 hello,

I've landed here from google search. I have the same issue as @slopes321 
I think that this behavior of emotion breaks "Cascading" word from CSS acronym.

I've prepared similar plain CSS codesandbox with that case, where it works properly: https://codesandbox.io/s/css-overrides-media-query-h4k6x

And the bit simplified case from the original report: https://codesandbox.io/s/emotion-issue-template-forked-2qe42?file=/src/index.js
```js
const BaseBox = styled("div")`
  background-color: yellow;
  @media screen and (min-width: 768px) {
    background-color: red;
  }
  background-color: lightblue;
`;
```
where I think background should be `lightblue`, but it's not.

From the generated code I see that above example is generated as 
```css
.css-1qgp6uu-BaseBox{background-color:yellow;background-color:lightblue;}

@media screen and (min-width:768px){.css-1qgp6uu-BaseBox{background-color:red;}}
```
so the order of rules is in fact changed. To keep cascading work properly we should divide it into three parts:
```css
.css-1qgp6uu-BaseBox{background-color:yellow}

@media screen and (min-width:768px){.css-1qgp6uu-BaseBox{background-color:red;}}

.css-1qgp6uu-BaseBox{background-color:lightblue;}
```

Could you please provide some more details why it can't work like in the CSS? Are there some code limitations?
Thanks in advance!

**Comment by Andarist** [comment]
@bukowskiadam I believe that this post covers the topic pretty extensively, please take a read: https://github.com/emotion-js/emotion/issues/1860#issuecomment-643435681 . I'm happy to discuss further if needed but not sure if I will have anything new to say in this regard beyond what is in that post and in that issue as a whole.

**Comment by bukowskiadam** [comment]
I think you miss the point with SCSS - you're right with mixins but we override styles for class names like
```scss
.test {
  color: red;
  @media screen {
    color: blue;
  }
}

.test {
  color: green;
}
```
and that doesn't work the same in scss and emotion.

To give you an example I've created a sample code (I had some problems with codesandbox, so here is the working app: https://scss-to-emotion.netlify.app/ and gh code https://github.com/bukowskiadam/scss-to-emotion/blob/master/src/App.js This is a sample code based on our real life project.
