### ISSUE TITLE
Css classes are not splitted to treat output CSS effectively

### ISSUE THREAD

**Issue by adambisek** [emotion-js/emotion#1741]
After reading documentation and googling I nowhere found, how to make Emotion effective and split produced css code.

**Version of Emotion:**
I have this issue on latest v 10.

**Repro steps:**
I have component like this:

```javascript
import styled from '@emotion/styled'

const StyledInput = styled.input`
  box-sizing: border-box;
  border: slim;
  border-color: red;
  color: ${(props: any) => myfunction(props.color || 'black')};
  width: 100%;
`
```

And I use it two times like this:

```javascript
<StyledInput color="red" />
<StyledInput color="green" />
```

**Current CSS output:**
```css
.class1 {
  box-sizing: border-box;
  border: slim;
  border-color: red;
  color: red;
  width: 100%;
}
.class2 {
  box-sizing: border-box;
  border: slim;
  border-color: green;
  color: red;
  width: 100%;
}
```

**Expected CSS output:**
```css
.commonClass {
  box-sizing: border-box;
  border: slim;
  border-color: red;
  width: 100%;
}
.class1 {
  color: red;
}
.class2 {
  color: red;
}
```
