### ISSUE TITLE
autoLabel: "dev-only" babel plugin option causes `cx` to merge styles inconsistently between dev and production builds

### ISSUE THREAD

**Issue by Gyanreyer** [emotion-js/emotion#2305]
**Current behavior:**

I have been running into an issue where emotion styles composed together with the `cx` method from `@emotion/css` will occasionally turn out differently between my development and production builds. For instance, locally my generated class for a link will turn out like this:
```css
.css-jy2kru-baseLinkStyle-buttonThemeStyle-getUnderlineModeStyle-disableFocusOutlineStyle-inherit-desktopHeaderLinkStyle {
    position: relative;
    -webkit-transition: all 0.2s;
    transition: all 0.2s;
    color: #11111E;
    -webkit-text-decoration: none;
    text-decoration: none;
    font-size: inherit;
    font-weight: inherit;
    line-height: inherit;
    letter-spacing: inherit;
    padding: 20px;
    text-transform: uppercase;
}
```
but in a production build, it turns out like this:
```css
.css-18kopqa {
    position: relative;
    transition: all 0.2s ease 0s;
    color: rgb(17, 17, 30);
    text-decoration: none;
    font-size: inherit;
    font-weight: inherit;
    line-height: inherit;
    text-transform: uppercase;
}
```

Obviously some of these differences are normal and to be expected, but notably, the `padding: 20px` style is missing which is causing major styling issues.

I was actually able to find a workaround for this by changing the babel plugin's `autoLabel` option from `dev-only` to `always`, but this is certainly not intended behavior. For the record, this results in the generated class in my production build turning out like this:
```css
.css-jy2kru-baseLinkStyle-buttonThemeStyle-getUnderlineModeStyle-disableFocusOutlineStyle-inherit-desktopHeaderLinkStyle {
    position: relative;
    transition: all 0.2s ease 0s;
    color: rgb(17, 17, 30);
    text-decoration: none;
    font-size: inherit;
    font-weight: inherit;
    line-height: inherit;
    letter-spacing: inherit;
    padding: 20px;
    text-transform: uppercase;
}
```

**To reproduce:**

This is what all of the involved emotion styles look like (note that all underlying logic here is removed, this just shows what styles are being combined in the end):

```js
const baseLinkStyle = css`
  position: relative;
  transition: all 0.2s;
`;

const buttonThemeStyle = css({
  color: '#11111E',
  '&:hover': {
    color: '#1a1a2e',
  },
});

const disableFocusOutlineStyle = css`
  &:focus {
    outline: none;
  }
`;

const underlineModeStyle = css`
  text-decoration: none;

  &:hover {
    text-decoration: none;
  }
`

const inheritTextStyle = css`
  font-size: inherit;
  font-weight: inherit;
  line-height: inherit;
  letter-spacing: inherit;
`;

const defaultTextStyle = inheritTextStyle;

// External class shared between a few different components
const desktopHeaderLinkStyle = css`
 ${inheritTextStyle}

  padding: 20px;
  text-transform: uppercase;

  &:first-child {
    margin-left: 0;
  }

  &:last-child {
    margin-right: 0;
  }
`;

cx(
  baseLinkStyle,
  defaultTextStyle,
  buttonThemeStyle,
  underlineModeStyle,
  {
    [disableFocusOutlineStyle]: true,
  },
  desktopHeaderLinkStyle,
)
```

My guess is that this has something to do with `inheritTextStyle` and the fact that it is present twice through both `defaultTextStyle` and `desktopHeaderLinkStyle`.

**Environment information:**

- `react` version: 16.8.6
- `@emotion/css` version:  11.1.3
- `@emotion/babel-plugin` version: 11.2.0
