### ISSUE TITLE
Composition duplicates css rules by creating different classes for each css block

### ISSUE THREAD

**Issue by jashwant** [emotion-js/emotion#2410]
**Current behavior:**

**To reproduce:**

1.  I created a button component.

```typescript

import { css, useTheme } from '@emotion/react';

type Props = { 
  colorScheme: 'primary' | 'secondary';
  children: React.ReactNode;
};
const Button = ({colorScheme = 'primary', children }: Props) => {
  const theme = useTheme();

  const baseCss = css`
    display: inline-block;
    color: #212529;
    background-color: transparent;
  `;

  let colorSchemeCss;

  if (colorScheme === 'primary') {
    colorSchemeCss = css`
      background-color: ${theme.color.primary};
    `;
  }

  return (
    <button type="button" css={[baseCss, colorSchemeCss]}>
      {children}
    </button>
  );
};

export default Button;
```
2. I am using it like this,

```jsx
<Button>
    Primary
 </Button>

<Button colorScheme="secondary">
   Secondary
 </Button>
```
3. Primary button is generating following css:

```css
   .css-o7ghp1-baseCss-colorSchemeCss-Button {
      display: inline-block;
      line-height: 1.5;
      color: #212529;
      background-color: red;
    }
```
    
Secondary button is generating following css:

```css
    .css-1fcrce4-baseCss-Button {
          display: inline-block;
          line-height: 1.5;
          color: #212529;
      }
```

**Expected behavior:**

Both buttons should have 1 same class with common rules. 

And primary button should have 1 additional class with a single rule `background-color: red` to avoid duplication of rules.

**Environment information:**

- `react` version: ^17.0.1
- `@emotion/react` version: ^11.1.5

I have even tried to not pass array in `css` but a single string by concatenating  baseCss and colorSchemeCss. It still generates duplicate rules ( however class names are different ).
