### ISSUE TITLE
Potential 5x perf improvement for stylesheet updates by switching to `CSSStyleSheet.replaceSync`

### ISSUE THREAD

**Issue by Jarred-Sumner** [emotion-js/emotion#2501]
**The problem**

Currently, hot module reloading pages that use Emotion with React is about 8x slower than using [`CSSStyleSheet.replaceSync`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replaceSync) to update styles. 

Here are two Chrome profiles where the same CSS is updated on disk 1024 times, sleeping for 32ms between each update. In the first case, it's a `<Global>` React component, and in the second case, it's a `<link>` tag being hot reloaded

[with-emotion-react.json.gz](https://github.com/emotion-js/emotion/files/7308999/emotion-1024-style-updates.json.gz) - this one is using Emotion and the React Component is being re-imported each time. Note the difference in time spent on Rendering between the two profiles.

<img width="327" alt="CleanShot 2021-10-07 at 23 35 22@2x" src="https://user-images.githubusercontent.com/709451/136509597-7ebba591-e6c6-460a-b3ef-e710674de957.png">

[with-replaceSync.json.gz](https://github.com/emotion-js/emotion/files/7309000/1024-style-updates-in-32ms-intervals-via-replaceSync.json.gz) - this one is using `CSSStyleSheet.replaceSync`

<img width="359" alt="CleanShot 2021-10-07 at 23 35 11@2x" src="https://user-images.githubusercontent.com/709451/136509565-93dc341d-ec40-45e1-b867-0f98df301183.png">

This is the CSS:
```css
:root {
  --timestamp: "16336741341477";
  --interval: "32";
  --progress-bar: 56.889%;
  --spinner-1-muted: rgb(179, 6, 202);
  --spinner-1-primary: rgb(224, 8, 253);
  --spinner-2-muted: rgb(22, 188, 124);
  --spinner-2-primary: rgb(27, 235, 155);
  --spinner-3-muted: rgb(89, 72, 0);
  --spinner-3-primary: rgb(111, 90, 0);
  --spinner-4-muted: rgb(18, 84, 202);
  --spinner-4-primary: rgb(23, 105, 253);
  --spinner-rotate: 304deg;
}
```

This is the React component using Emotion:
```tsx

import { Global } from "@emotion/react";
export function CSSInJSStyles() {
  return (
    <Global
      styles={`
:root {
  --timestamp: "16336721342556";
  --interval: "32";
  --progress-bar: 56.889%;
  --spinner-1-muted: rgb(179, 6, 202);
  --spinner-1-primary: rgb(224, 8, 253);
  --spinner-2-muted: rgb(22, 188, 124);
  --spinner-2-primary: rgb(27, 235, 155);
  --spinner-3-muted: rgb(89, 72, 0);
  --spinner-3-primary: rgb(111, 90, 0);
  --spinner-4-muted: rgb(18, 84, 202);
  --spinner-4-primary: rgb(23, 105, 253);
  --spinner-rotate: 304deg;
}  `}
    />
  );
}
```

**Proposed solution**

Detect if [`CSSStyleSheet.replaceSync`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replaceSync) is supported in the current browser and use that to update the existing stylesheet (rather than creating a new one). This would work for both development and production (in production for dynamic styles).

Drawbacks:
- This API is only available in Chromium browsers. Multiple "backends" for updating styles introduces complexity
- `@import` is not supported with `CSSStyleSheet.replaceSync`

**Alternative solutions**

**Additional context**

`replaceSync` has some cost, but it's not so bad:

<img width="391" alt="CleanShot 2021-10-07 at 23 58 24@2x" src="https://user-images.githubusercontent.com/709451/136512305-9c5a9e93-73bc-4e19-bd1c-5ae13c8aa126.png">

Versus:

<img width="407" alt="CleanShot 2021-10-07 at 23 58 53@2x" src="https://user-images.githubusercontent.com/709451/136512367-ee97033b-3bd9-4b69-be21-fb3b6c857618.png">

Incase opening the profiles are a pain, here are screenshots.

Emotion:
<img width="977" alt="CleanShot 2021-10-08 at 00 09 54@2x" src="https://user-images.githubusercontent.com/709451/136513507-1a27cdb7-2456-4bab-b0bc-55207f80a840.png">

replaceSync:
<img width="982" alt="CleanShot 2021-10-08 at 00 08 16@2x" src="https://user-images.githubusercontent.com/709451/136513403-b7f93716-dcb6-4746-84f2-2dbcf2cae7a4.png">
