### ISSUE TITLE
Class name interpolation no longer works when switching to `@emotion/css` 11.1.3

### ISSUE THREAD

**Issue by cameron-mcateer** [emotion-js/emotion#2504]
**Current behavior:**

Interpolating class names generated by emotion's `css` function into nested selectors causes unexpected style generation.
What we really want is to be able specify child behavior when a parent is hovered (or when other pseudo-classes apply).

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-forked-255b9
The text directly inside the parent turns blue. The following code:

```js
const childClass = css`
  color: red;
`;

const parentClass = css`
  color: green;

  &:hover {
    .${childClass} {
      color: blue;
    }
  }
`;
```

outputs the following css:
```css
.css-zva02e-child{color:red;}
.css-1508fcg-parent-child{color:green;}
.css-1508fcg-parent-child:hover{. label:child;color:red;}
.css-1508fcg-parent-child:hover {color:blue;}
```

**Expected behavior:**

When hovering over the parent div, the specified child div should its font color change to blue.

CSS output should be something like the following:
```css
.css-zva02e-child{color:red;}
.css-1508fcg-parent{color:green;}
.css-1508fcg-parent:hover .css-zva02e-child{color:blue;}
```

**Environment information:**

- `react` version: 16.8.6
- `@emotion/css` version: 11.1.3
