### ISSUE TITLE
Use a custom PostCSS plugin for expanding nested selectors for static styles

### ISSUE THREAD

**Issue by mitchellhamilton** [emotion-js/emotion#264]
Currently we use `postcss-nested` to expand nested selectors. This causes a problem because it's inconsistent with the way we expand styles without `extractStatic`.

For example,
```jsx
const cls = css`
  .some-class {
    background-color: hotpink;
  }
`
```
will expand to this without `extractStatic`
```css
.css-hash.some-class {
  background-color: hotpink;
}
```
but it will expand to this with `extractStatic`
```css
.css-hash .some-class {
  background-color: hotpink;
}
```
