### ISSUE TITLE
Animation and nested selector

### ISSUE THREAD

**Issue by ai** [emotion-js/emotion#288]
- `emotion` version: 7.2.0
- `react` version: 15.6.1

Relevant code.

```javascript
const blink = keyframes`
  66% {
    opacity: 1;
  }
  66.1% {
    opacity: 0.2;
  }
  to {
    opacity: 0.2;
  }
`
const wifiBlink = css`
  path {
    animation: 700ms linear 0ms infinite ${ blink };
  }
`

<Icon className={ wifiBlink }/>
```

What you did:

No animation. Inserted styles are:

```css
.css-1mkqzc1path{-webkit-animation:700ms linear 0ms infinite css-blink-lz04i3;animation:700ms linear 0ms infinite css-blink-lz04i3;}
```

What happened:

Animation for each SVG `<path>` and inserted CSS (space in selector):

```css
.css-1mkqzc1 path{-webkit-animation:700ms linear 0ms infinite css-blink-lz04i3;animation:700ms linear 0ms infinite css-blink-lz04i3;}
```

Problem description:

Seems like there is a conflict of nested selectors and animation

**Comment by DaniilTomilow** [comment]
I think the '&' selector is necessary here:

```js
const wifiBlink = css`
  & path {
    animation: 700ms linear 0ms infinite ${ blink };
  }
`
```

**Comment by ai** [comment]
@DaniilTomilow yeap `& ` helps. But it is not expected, so it is not good for new developers.

**Comment by DaniilTomilow** [comment]
[Emotion 7](https://medium.com/@tkh44/emotion-7-7ef119c45869): 
> Important breaking change that was not mentioned here:
You now have to prefix nested CSS selectors with an ampersand (&) (ala LESS, SASS, etc.).
e.g. ~ Darren Torpey
```js
ul {
 & li {
…
}
}
```
So `&` is expected here, or?

**Comment by ai** [comment]
Ouh, I missed it. Maybe we should throw a error on missed `&`? It is very popular Sass patern and many new developers will leave same mistake.

**Comment by DaniilTomilow** [comment]
This would make sense. Without the `&`, the selectors are parsed to invalid css properties e.g:
```js
css`
  span { 
    color: red;
  }
`
```
Is compiled to:
```css
.css-xxx {
  span: [object Object]
}
```
