### ISSUE TITLE
"Fallback" property values do not seem to work

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2894]
We have the following [example](https://emotion.sh/docs/object-styles#fallbacks) in our docs:

```tsx
render(
  <div
    css={{
      background: ['red', 'linear-gradient(#e66465, #9198e5)'],
      height: 100
    }}
  >
    This has a gradient background in browsers that support gradients and is red
    in browsers that don't support gradients
  </div>
)
```

Using the element inspector shows that the actual generated CSS is:

```css
.css-o8gz82 {
    background: linear-gradient(rgb(230, 100, 101), rgb(145, 152, 229));
    height: 100px;
}
```

Presumably it should be:

```css
.css-o8gz82 {
    background: red;
    background: linear-gradient(rgb(230, 100, 101), rgb(145, 152, 229));
    height: 100px;
}
```

This was reported in our Slack:

> is the fallback-values api removed or broken? in development builds i get all values but in production only the last item of the array is added (we use webpack + mui + tss-react)=?

So apparently it still works in development builds.
