### ISSUE TITLE
Reimplement component selectors

### ISSUE THREAD

**Issue by probablyup** [emotion-js/emotion#461]
Based on this convo: https://twitter.com/probablyup/status/928552573057097728

Action items:

1. Generate a second, stable hashed `className` for each `styled` component and tag it as a static property like `__emotion_target` (it should not change based on the style content of the component, but using `withComponent` should generate a new target)

2. When interpolating a component, `__emotion_target` should be used to create the selector.

The end result should look like this:

```js
import styled from 'react-emotion';

const StyledThing = styled.div`
    color: blue;
`;

const StyledOtherThing = styled.div`
    color: red;

    ${StyledThing} {
        color: green;
    }
`;
```

and emits CSS like:

```css
.{dynamicHash}-StyledThing { color: blue }
.{dynamicHash}-StyledOtherThing { color: red }
.{dynamicHash}-StyledOtherThing .{stableHash}-StyledThing { color: green }
```
