### ISSUE TITLE
Emotion adds px to unitless custom properties

### ISSUE THREAD

**Issue by TrySound** [emotion-js/emotion#479]
- `emotion` version: 8.0.11
- `react` version: 16.2

Relevant code.

```javascript
const Icon = styled('div')({
  ':hover': {
    '--opacity': 0.4
  }
});
```

What happened:
```css
.css-14h7is1:hover {
    --opacity: 0.4px;
}
```

Problem description:
Custom properties should not add units

Suggested solution:
...
