### ISSUE TITLE
Emotion css parser does not support selectors over multiple lines

### ISSUE THREAD

**Issue by einarlove** [emotion-js/emotion#481]
- `emotion` version: 8.0.10
- `react` version: 16.2.0

**Relevant code**

```javascript
css`
  .my-class:hover
  .its-child {
    background: pink;
  }
`
```

**Outputs**
```css
.my-class:hover;
.its-child { background: pink; }
```

**Expected**
```css
.my-class:hover .its-child { background: pink; }
```

In the CSS spec you can have selectors over multiple lines, but in my experience emotion does not.
This gets even more problematic when [Prettier](https://github.com/prettier/prettier) formats the code to be within set line width.
