### ISSUE TITLE
Object styles with line clamp adding 'px'

### ISSUE THREAD

**Issue by jschr** [emotion-js/emotion#561]
`emotion` version: 8.0.12
`react` version: 16.0.0

Relevant code.

```javascript
css({ 
  WebkitLineClamp: 4 
})
```

What happened:

```css
{
  -webkit-line-clamp: 4px;
}
```

Expected:
```css
{
  -webkit-line-clamp: 4;
}
```

Reproducible:
https://codesandbox.io/s/430pkxw90x

Workarounds:
```js
css`
  -webkit-line-clamp: 4;
`
```
```js
css({
  ' -webkit-line-clamp': 4
})
```
^ note the first space before the `-`.
