### ISSUE TITLE
Update docs with ampersand use examples

### ISSUE THREAD

**Issue by giocodes** [emotion-js/emotion#724]
@tkh44 great job on the library 👍 👍 

- `emotion` version: v9.2.3
- `react` version: 16.2.0

The current documentation mentions [child selectors](https://emotion.sh/docs/object-styles#child-selectors), I believe it might be useful to clarify what the ampersand character does and some uses.  

For example:
**To increase specificity:**
```javascript
const style = css({
  '.ui.menu&&': {
    color: 'red',
  },
});
```
```css
/* Any occurrence of '&' is replaced with the generated class name */
.ui.menu.abc123.abc123 {
  color: red;
}
```

There are some other examples that could be documented as glamorous does:
https://github.com/paypal/glamorous/blob/8a21d8b85aafccf86198d62463d97b6fd6c45368/examples/README.md#ampersands--css-combinators
